### ISSUE TITLE
what is the gesture recognition server address

### ISSUE THREAD

**Issue by TuGengs** [CoderEugene/DL-Gesture-Recognition#2]

**Comment by TuGengs** [comment]
gesture recognition server address

**Comment by fpanchoro** [comment]
you must lend the server because in the file gesture_rec calls three services post

**Comment by TuGengs** [comment]
Okay, But as /upload ---/category_network ----/remove  Now, Can you tell me how to build such a gesture server?

**Comment by fpanchoro** [comment]
I'm still trying to understand that the structure is being made, to do, a fictitious one will be executed, for example:

 json_string ='{"code": 0,"data":{"Doing other things": 0.10,"Drumming Fingers": 0.20,"No gesture": 0.3,"Pulling Two Fingers In": 0.4,"Pushing Two Fingers Away": 0.5,"Shaking Hand": 0.6,"Sliding Two Fingers Down": 0.7,"Swiping Left": 0.8,"Thumb Down": 0.9,"Thumb Up": 0.0409,"Zooming In With Full Hand": 0.11,"Zooming In With Two Fingers": 0.12,"Zooming Out With Full Hand": 0.13,"Zooming Out With Two Fingers": 0.14}}'
        res =json.loads(json_string)

It is important to mention that this structure helps it to run, but it does not cause it to do so with a correct prediction.

I am studying the code to try to do it well

**Comment by fpanchoro** [comment]
An exercise can be substituted for this version of tensorflow.js

https://js.tensorflow.org/tutorials/webcam-transfer-learning.html

**Comment by govzhz** [comment]
see update
